name: Alphie
namespace: bf-alphie
defaultLanguage: en
nluThreshold: 0.75
timezoneOffset: 0
allowContextualQuestions: false
instance:
  name: Default Instance
  host: 'http://rasa:5005'
  projectId: wAsn83znKFznRaWFy
